name: Build - Test

on:
  push:
  workflow_dispatch:

jobs:
  build_parameters:
    name: Define Build Parameters
    runs-on: ubuntu-latest
    # We need to share details across job boundaries, expose the step outputs at the job level
    outputs:
      maven_changelist: ${{ steps.build_params.outputs.maven_changelist }}
      maven_sha1: ${{ steps.build_params.outputs.maven_sha1 }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Define Build Parameters
        id: build_params
        uses: actions/github-script@v7
        with:
          script: |
            const scriptPath = require('path').resolve('./.github/workflows/scripts/buildParameters.js')
              , buildParameters = require(scriptPath);
            ;
            buildParameters(context, core).injectBuildParameters();

  build_and_test:
    name: Build & Test Java 11 on ubuntu-latest
    runs-on: ubuntu-latest
    needs:
      - build_parameters
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          java-package: jdk
          distribution: temurin
          cache: maven

      - name: Build Test and Package
        run: |
          mvn package -B \
            -Dsha1="${{ needs.build_parameters.outputs.maven_sha1 }}" \
            -Dchangelist="${{ needs.build_parameters.outputs.maven_changelist }}" \
            -Dgithub.repository="${GITHUB_REPOSITORY}"
